### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_optional_access'

### ISSUE THREAD

**Issue by Lu0su** [archibate/co_async#14]
完整错误如下: 
terminate called after throwing an instance of 'std::bad_optional_access'
what():  bad optional access
fish: Job 1, './build/test_co_async' terminated by signal SIGABRT (Abort)

在examples/chat_server运行时，当我在浏览器中输入用户名，按下登陆按钮后，出现了这个问题，请问您知道为啥吗？
我的环境是: 5.15.133.1-microsoft-standard-WSL2 内核版本有点低，但是已经开启了相应的选项，并且连接过程没有问题
难道还是由于内核版本太低导致的吗？

**Comment by archibate** [comment]
不支持wsl，因为我发现iouring需要linux 6.0才有完整支持，而wsl的内核版本和wendous捆绑，是不能更新的。
